BREAKCODE                       = "======================="
INITIATED_LOGIN_API             = "Initaited the login api"
INITAITED_REGISTER_API          = "Initiated the user register api"
INITAITED_HOME_SCREEN_API       = "Initaited the home screen api"
INITAITED_SUBCAT_PRODUCT_API    = "Initaited the sub category product screen api"
INITAITED_PRODUCT_INFO_API      = "Initaited the product information screen api"
INITAITED_ORDER_HISTORY_API     = "Initaited the order history api"
INITAITED_PLACE_ORDER_API       = "Initaited the order place api"
INITAITED_ORDER_DETAILS_API     = "Initaited the order details api"
INITAITED_PLACE_LIST_API        = "Initaited the order details api"
INITAITED_ORDER_STATS_API       = "Initaited the order details api"

INITAITED_ADDRESS_INSERT_API    = "Initaited Address insert api"
INITAITED_ADDRESS_UPDATE_API    = "Initaited Address update api"

ERROR_MESSAGE           = "Invalid_Request"
